Syncer\Dto\InvoiceNinja\PostTaskResponse:
    exclusion_policy: ALL
    properties:
        data:
            type: Syncer\Dto\InvoiceNinja\Task
            serialized_name: data
            exclude: false
