Syncer\Dto\Toggl\DetailedReport:
    exclusion_policy: ALL
    properties:
        totalGrand:
            type: integer
            serialized_name: total_grand
            exclude: false
        totalBillable:
            type: integer
            serialized_name: total_billable
            exclude: false
        totalCount:
            type: integer
            serialized_name: total_count
            exclude: false
        perPage:
            type: integer
            serialized_name: per_page
            exlude: false
        data:
            type: array<Syncer\Dto\Toggl\TimeEntry>
            serialized_name: data
            exclude: false
